config/routes.rb
Handlasmidigt::Application.routes.draw do
    
  resources :lists

  get "pages/about"

  get "pages/index"

    devise_for :users

    root :to => "pages#index"

end

app/models/list.rb
class List < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :firstname, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = List.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    @list = List.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(params[:list])

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render json: @list, status: :created, location: @list }
      else
        format.html { render action: "new" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/home/index.html.erb
<h3>Home#index</h3>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<% # encoding: UTF-8 %>
<!DOCTYPE html>
<html>
<head>

  <title>
  <% if user_signed_in? %>
    Inköpslistan | <%= current_user.firstname.capitalize %>
  <% else %>
    Inköpslistan
  <% end %>
 </title>

  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Ubuntu:400,700' rel='stylesheet' type='text/css'>
</head>
<body>

<div id="container">
  
  <div id="logo">
  <h1>Inköpslistan.se</h1>
  </div>

<div id="info">
    <% if user_signed_in? %>
      Inloggad som <%= current_user.firstname %> -
      <%= link_to "Logga ut", destroy_user_session_path, :method => :delete %><br />
      <%= link_to "Min Profil", edit_user_registration_path %>
    <% else %>
      <%= link_to "Logga in", new_user_session_path %> eller 
      <%= link_to "Registrera", new_user_registration_path %>
    <% end %>    
</div>
<div id="menu">
<ul>
<li><%= link_to "Startsidan", pages_index_path %></li>
<li><%= link_to "Inköpslistor", lists_path %></li>
<li><%= link_to "Om Inköpslistan", pages_about_path %></li>
<li>
</ul>
</div>

  <div class="text">
<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </div>
<div id="footer">
<p><a href="mailto:info@inkopslistan.se">info@inkopslistan.se</a><br />
Inköpslistan.se är en sida som är gratis för alla att använda, hör gärna av er med feedback och om ni har tips på hur vi kan förbättra sidan.</p>
</div>
</div>
</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :article1 %><br />
    <%= f.text_field :article1 %>
  </div>
  <div class="field">
    <%= f.label :article2 %><br />
    <%= f.text_field :article2 %>
  </div>
  <div class="field">
    <%= f.label :article3 %><br />
    <%= f.text_field :article3 %>
  </div>
  <div class="field">
    <%= f.label :article4 %><br />
    <%= f.text_field :article4 %>
  </div>
  <div class="field">
    <%= f.label :article5 %><br />
    <%= f.text_field :article5 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<% if user_signed_in? %>
  <h2>Redigera lista</h2>

  <%= render 'form' %>
  <br />
  <%= link_to 'Visa listan', @list %>
  <%= link_to 'Tillbaka', lists_path %>

<% else %>
  <h2>Redigera lista</h2>
  <p>Du måste <%= link_to 'logga in', new_user_session_path %> för att redigera en lista.</p>

<% end %>

app/views/lists/index.html.erb
<h2>Inköpslistor</h2>
<%= link_to 'Skapa ny lista', new_list_path %>
<br /><br />
<table width="700">
<tr align="left">
<th>Datum </th>
<th>Namnet på listan</th>
<th></th>
    <th></th>
</tr>
<% @lists.each do |list| %>
    <tr>
      <td><%= list.updated_at.strftime("%d/%m/%Y") %></td>
      <td><%= link_to list.title, list %></td>
      <td></td>
      <td>
      </td>
    </tr>
  <% end %>
</table>

app/views/lists/new.html.erb
<% if user_signed_in? %>
  <h2>Skapa ny lista</h2>

  <%= render 'form' %>

  <br />
  <%= link_to 'Tillbaka', lists_path %>

<% else %>

  <h2>Skapa ny lista</h2>
  <p>Du måste <%= link_to 'logga in', new_user_session_path %> för att skapa en lista.</p>

<% end %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @list.title %></h2>
<strike><%= @list.article1 %></strike><br />
<%= @list.article2 %><br />
<%= @list.article3 %><br />
<%= @list.article4 %><br />
<%= @list.article5 %><br />
<%= check_box_tag 'article1' , false %>


<br /><%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/pages/about.html.erb
<h2>Om Inköpslistan</h2>

app/views/pages/index.html.erb
<h2>Välkommen</h2>
<p>Inköpslistan.se är en gratistjänst och tanken är att det ska vara enklare att planera och handla samt dela med er av inköpslistor och recept till familj och vänner.</p>